//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cascad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstates2
    {
        public Nullable<int> coun_id1 { get; set; }
        public string states1 { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
